### ISSUE TITLE
Share with the entire ansible community?

### ISSUE THREAD

**Issue by cidrblock** [ansible-community/antsichaut#16]
Hey there @rndmh3ro,

I work on a team inside Ansible called devtools. We work with the broader ansible community to maintain tools like ansible-lint, ansible-navigator, molecule, and the VS Code extention for ansible.

We are also working bringing together all of the tools someone would need to test, lint, and release collections.

I think antsichaut would be a great addition to that list of tools.

I'm curious if you would be interesting in tranferring it to the `ansible-community` organization in Github.  We of course can keep you as an owner but we would also add the devtools team.

The devtools team could help sync it's CI/CD pipeline and tool kit to line up with some of the other repos we maintain.  This could include things like black, ruff, darglint, mypy, pylint and pre-commit. 

Let me know if you are interested, if not, that's ok of course. We could just fork it and run with it (attribution always manitained), but in my mind that's always last resort since the 2 repos can quickly get out of sync and could confuse people over time.

Hope you had a great vacation, please let me know what you think

Brad

**Comment by rndmh3ro** [comment]
Hey Brad,

that sounds great, let's go ahead and do this. I'd still like to be a maintainer. :)

My vacation was great, btw. However i got sick right afterwards and will be the whole week. So I won't really have time to do something until maybe the weekend (still need to review #15!).

**Comment by cidrblock** [comment]
Excellent!

I'm not sure if you can transfer it to `ansible-community` or not, you may have to be an admin in that org.  You can try, LMK.

If you can't do it, you will probably have to add me add me as an owner here so I can do the tranfer. 

Once done, I will absolutley add you as a maintainer :)

keep me posted, Brad

**Comment by rndmh3ro** [comment]
I cannot transfer it:

> You don’t have the permission to create public repositories on ansible-community

I invited you as a colloborator, however I think that you cannot then transfer the repo.

Yiu probably have to invite me into ansible-community and give me permission to create repos. Then I can transfer it. Then you can remove the permission again.

**Comment by ssbarnea** [comment]
Make request to transfer the repo to @cidrblock and he will move it. Sadly github defaults require this two step process for all cases where the donator does not have create-public-repo permission on target organization,... which is likely 9/10 case :p -- even their support told us to use this workaround.

**Comment by rndmh3ro** [comment]
@cidrblock to do this you have to delete your fork first. :)

**Comment by cidrblock** [comment]
```
Your repository "cidrblock/antsichaut" was successfully deleted.  
```
done :)

Good idea Sorin
