### ISSUE TITLE
Label for skipping changelog

### ISSUE THREAD

**Issue by gardar** [ansible-community/antsichaut#3]
It would be good to have a label for PR's to skip the changelog, for example to avoid adding PR's that only contain changes related to the  ci of a project into the ansible collection changelog.

**Comment by rndmh3ro** [comment]
Good idea! Something like skip-changelog`. Do you want to implement it?

**Comment by rndmh3ro** [comment]
implemented in 7e84c08c2395cfcca5bba4163c846f0130f7d393
